# Generated by Django 3.1 on 2020-08-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200826_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('withdrawal', 'withdrawal'), ('deposit', 'deposit')], max_length=60),
        ),
    ]
